### ISSUE TITLE
Remove unused sections from drawer for first app release

### ISSUE THREAD

**Issue by sderungs99** [sderungs99/sglandtransport#27]
- Hide behind a feature toggle?
- Use https://pub.dev/packages/firebase_remote_config?
- Use https://pub.dev/packages/feature_flag?

**Comment by bobrenji** [comment]
I will use local feature toggle for handling this

**Comment by bobrenji** [comment]
Add Release Toggles. These are feature flags used to enable branch based development for us practicing continuous enhancment.
