### ISSUE TITLE
Display of Advisement Messages/Status in UI, when there is NO Bus Arrival Data

### ISSUE THREAD

**Issue by bobrenji** [sderungs99/sglandtransport#32]
- Arrival data is available => (none required)
- Bus is in operation and Arrival data is NOT available  => “No Est. Available”
- Bus is NOT in operation  and Arrival data is NOT available => “Not In Operation”
- Bus is NOT in operation  and Arrival data is available =>  (none required)

Reference - https://www.mytransport.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf

**Comment by sderungs99** [comment]
I'm starting with this...

**Comment by sderungs99** [comment]
Implemented and pushed to develop branch
