### ISSUE TITLE
Fix ui automation issue

### ISSUE THREAD

**Issue by bobrenji** [sderungs99/sglandtransport#70]
- Unable to run automation locally
- Not able to start simulator
- Should accept permission alert by code
- How to mock/solve the DB dependecy
- Stuck due to the animation

**Comment by sderungs99** [comment]
Looks like it is stuck due to our Splash() component. When I remove that, the tests start successfully (at least until the accept permission alert is appearing).

**Comment by sderungs99** [comment]
Regarding accept permission alert, maybe we can mock our LocationProvider somehow when the app is called via UI tests? Meaning when called through a UI test, we somehow have a flag that ensures we are not actually querying the position, but hardcode something?

**Comment by sderungs99** [comment]
completed by passing in a command line attribute, based on which the animation will be put on idle and the location will be hardcoded without asking for permission to access location.
